### ISSUE TITLE
add to the client the LastApprovedDate and ApproverName

### ISSUE THREAD

**Issue by mdah90** [org-tatbiq-tech/AleenNails_admin#51]

**Comment by ghost** [comment]
is this done ? I see acceptedDay tag

**Comment by mdah90** [comment]
no .. i didn't add this acceptedDate

**Comment by mdah90** [comment]
i want to add 
lastApprovalEditorId
lastApprovalEditDate 
and to update it each time the admin approve/deny (because he always can toggle this value)
