### ISSUE TITLE
being in day view and changing day->month cause state issue

### ISSUE THREAD

**Issue by ghost** [org-tatbiq-tech/AleenNails_admin#57]
* Be in main page in appointments application
* Change to day view
* click on month/day
* 
![image](https://user-images.githubusercontent.com/72263981/206870398-ec055a6b-f9c8-4672-afa1-d3e1f41b184c.png)

See trace below:

======== Exception caught by widget library ========================================================
The following assertion was thrown while dispatching notifications for ScrollNotificationObserverState:
setState() or markNeedsBuild() called during build.

This AppBar widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: AppBar
  dependencies: [FlexibleSpaceBarSettings, MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#0d00e], _ModalScopeStatus, _ScrollNotificationObserverScope]
  state: _AppBarState#a4530
The widget which was currently being built when the offending call was made was: Flexible
  flex: 0
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4549:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4564:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1134:15)
#3      _AppBarState._handleScrollNotification (package:flutter/src/material/app_bar.dart:853:9)
#4      ScrollNotificationObserverState._notifyListeners (package:flutter/src/widgets/scroll_notification_observer.dart:135:25)
#5      ScrollNotificationObserverState.build.<anonymous closure> (package:flutter/src/widgets/scroll_notification_observer.dart:171:11)
#6      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3094:18)
#8      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
#9      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
#10     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
#11     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
#12     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
#13     Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4441:24)
#14     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#15     ScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:92:92)
#16     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:914:15)
#17     ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:199:7)
#18     PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:220:14)
#19     _TableCalendarBaseState._updatePage (package:table_calendar/src/table_calendar_base.dart:175:23)
#20     _TableCalendarBaseState.didUpdateWidget (package:table_calendar/src/table_calendar_base.dart:121:7)
#21     StatefulElement.update (package:flutter/src/widgets/framework.dart:5065:57)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#27     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#28     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#33     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#41     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#44     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#46     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#52     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#58     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#65     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#68     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#70     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#76     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#82     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#86     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#88     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#89     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#91     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#92     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#96     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#100    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#104    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#108    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#112    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#114    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#115    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#119    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#122    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#124    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#127    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#129    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#133    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#136    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#138    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#140    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#144    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#146    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#149    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#151    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#154    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#155    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#156    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#160    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#164    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#168    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#171    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#172    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#173    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#174    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#176    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#177    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#180    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#182    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#185    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#186    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#187    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#188    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#189    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#191    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#192    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#193    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#194    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#196    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#197    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#198    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#200    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#201    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#202    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#204    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#205    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#206    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#207    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#208    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#209    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#210    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#211    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#212    _invoke (dart:ui/hooks.dart:148:13)
#213    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#214    _drawFrame (dart:ui/hooks.dart:115:31)
The ScrollNotificationObserverState sending notification was: ScrollNotificationObserverState#55b12
====================================================================================================

**Comment by ahmadmnaa** [comment]
Issue is not reproducible  in my device

**Comment by ghost** [comment]
this is why im reporting the log
