### ISSUE TITLE
open appointment details crash the appointment app / or stuck with waiting indicator

### ISSUE THREAD

**Issue by mdah90** [org-tatbiq-tech/AleenNails_admin#59]
![image](https://user-images.githubusercontent.com/56922069/207158356-e9ee66fb-c55e-4f96-a90b-9a5cd8eece37.png)

full stack:
======== Exception caught by widgets library =======================================================
The following LateError was thrown building Builder:
LateInitializationError: Field '_selectedAppointment@2466237960' has not been initialized.

The relevant error-causing widget was: 
  AnimatedSwitcher AnimatedSwitcher:file:///C:/Users/muham/StudioProjects/appointments/lib/main.dart:180:21
When the exception was thrown, this was the stack: 
#0      AppointmentsMgr._selectedAppointment (package:appointments/providers/appointments_mgr.dart)
#1      AppointmentsMgr.selectedAppointment (package:appointments/providers/appointments_mgr.dart:136:12)
#2      AppointmentDetailsState.initState (package:appointments/screens/home/appointments/appointment_details.dart:48:36)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (275 frames)
#279    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#280    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#281    Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#282    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5964:32)
#283    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#284    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#285    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#286    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#287    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#288    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#289    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#290    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#291    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#292    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#293    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#294    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#295    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#296    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#297    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#298    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#299    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#300    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#301    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#302    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#303    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#304    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#305    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#306    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#307    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#308    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#309    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#310    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#311    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#312    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#313    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#314    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#315    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#316    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#317    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#318    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#319    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#320    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#321    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#322    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#323    _invoke (dart:ui/hooks.dart:148:13)
#324    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#325    _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================

**Comment by mdah90** [comment]
did you push this fix .. because i still see this crash 
The relevant error-causing widget was: 
  AnimatedSwitcher AnimatedSwitcher:file:///C:/Users/muham/StudioProjects/appointments/lib/main.dart:180:21
When the exception was thrown, this was the stack: 
#0      AppointmentsMgr._selectedAppointment (package:appointments/providers/appointments_mgr.dart)
#1      AppointmentsMgr.selectedAppointment (package:appointments/providers/appointments_mgr.dart:136:12)
#2      AppointmentDetailsState.initState (package:appointments/screens/home/appointments/appointment_details.dart:48:36)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (275 frames)
#279    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#280    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#281    Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#282    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5964:32)
#283    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#284    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#285    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#286    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#287    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#288    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#289    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#290    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#291    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#292    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#293    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#294    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#295    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#296    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#297    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#298    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#299    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#300    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#301    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#302    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#303    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#304    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#305    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#306    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#307    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#308    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#309    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#310    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#311    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#312    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#313    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#314    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#315    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#316    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#317    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#318    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#319    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#320    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#321    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#322    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#323    _invoke (dart:ui/hooks.dart:148:13)
#324    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#325    _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================

**Comment by ahmadmnaa** [comment]
We have another issue I fixed.
code pushed
