### ISSUE TITLE
client edit issues

### ISSUE THREAD

**Issue by mdah90** [org-tatbiq-tech/AleenNails_admin#62]
- admin can change connected email (changed MD1 email)
- admin can change connected phone number(changed MD1 email)
- updating client details (like name) is not reflected in appointments collection

**Comment by ghost** [comment]
If we want to prevent admin from changing email and phone, we need to make sure that this account is registered and attached to real user. 
means, normal users added by the admin, its ok to change it 

What do you think ? 
@ahmadmnaa @mdah90

**Comment by ghost** [comment]
I have fixed the third part, if client details has been updated, then all appointments will be updated accordingly

**Comment by ahmadmnaa** [comment]
there is one more issue in client 
go to clients select some client in go to edit mode, change the name and try to save 
admin can't change the name we getting error message existing  mail change it and try again.

**Comment by ghost** [comment]
Fixed
