### ISSUE TITLE
crash after deny client from Approval_request.dart + from notification action

### ISSUE THREAD

**Issue by mdah90** [org-tatbiq-tech/AleenNails_admin#63]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#623ea](dirty, state: _OverlayEntryWidgetState#e5c3a):
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

The relevant error-causing widget was: 
  AnimatedSwitcher AnimatedSwitcher:file:///C:/Users/muham/StudioProjects/appointments/lib/main.dart:180:21
When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4241:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4255:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4275:12)
#3      Theme.of (package:flutter/src/material/theme.dart:108:53)
#4      showSuccessFlash.<anonymous closure> (package:common_widgets/utils/flash_manager.dart:109:26)
#5      FlashController._createOverlayEntries.<anonymous closure> (package:flash/flash.dart:170:27)
#6      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:256:34)
#7      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#11     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#13     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5986:32)
#14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#20     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#22     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#23     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#25     _invoke (dart:ui/hooks.dart:148:13)
#26     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#27     _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
setState() called after dispose(): _FlashState<dynamic>#343a1(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1078:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1113:6)
#2      _FlashState._handleStatusChanged (package:flash/flash.dart:885:11)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
#4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:822:7)
#5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:838:5)
#6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#8      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1079:11)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#10     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1077:17)
#11     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:994:5)
#12     _invoke1 (dart:ui/hooks.dart:167:13)
#13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:296:5)
#14     _beginFrame (dart:ui/hooks.dart:104:31)
The AnimationController notifying status listeners was: AnimationController#70757(⏭ 1.000; paused; for FlashController<Object?>)
====================================================================================================

**Comment by ghost** [comment]
@ahmadmnaa did you reproduce this issue ?
